sources = [
        {"original": "ActiveCampaign", "formatted": "source-activecampaign"},
        {"original": "Adjust", "formatted": "source-adjust"},
        {"original": "Aha", "formatted": "source-aha"},
        {"original": "Aircall", "formatted": "source-aircall"},
        {"original": "Airtable", "formatted": "source-airtable"},
        {"original": "Alpha Vantage", "formatted": "source-alpha-vantage"},
        {"original": "Amazon Ads", "formatted": "source-amazon-ads"},
        {
            "original": "Amazon Seller Partner",
            "formatted": "source-amazon-seller-partner",
        },
        {"original": "Amazon SQS", "formatted": "source-amazon-sqs"},
        {"original": "Amplitude", "formatted": "source-amplitude"},
        {"original": "Apify Dataset", "formatted": "source-apify-dataset"},
        {"original": "Appfollow", "formatted": "source-appfollow"},
        {"original": "Apple Search Ads", "formatted": "source-apple-search-ads"},
        {"original": "AppsFlyer", "formatted": "source-appsflyer"},
        {"original": "Asana", "formatted": "source-asana"},
        {"original": "Ashby", "formatted": "source-ashby"},
        {"original": "Auth0", "formatted": "source-auth0"},
        {"original": "Avni", "formatted": "source-avni"},
        {"original": "AWS CloudTrail", "formatted": "source-aws-cloudtrail"},
        {"original": "Azure Blob Storage", "formatted": "source-azure-blob-storage"},
        {"original": "Azure Table Storage", "formatted": "source-azure-table"},
        {"original": "Babelforce", "formatted": "source-babelforce"},
        {"original": "BambooHR", "formatted": "source-bamboo-hr"},
        {"original": "Bing Ads", "formatted": "source-bing-ads"},
        {"original": "Braintree", "formatted": "source-braintree"},
        {"original": "Braze", "formatted": "source-braze"},
        {"original": "Breezometer", "formatted": "source-breezometer"},
        {"original": "CallRail", "formatted": "source-callrail"},
        {"original": "Captain Data", "formatted": "source-captain-data"},
        {"original": "Cart.com", "formatted": "source-cart"},
        {"original": "Chargebee", "formatted": "source-chargebee"},
        {"original": "Chargify", "formatted": "source-chargify"},
        {"original": "Chartmogul", "formatted": "source-chartmogul"},
        {"original": "ClickUp", "formatted": "source-clickup-api"},
        {"original": "Clockify", "formatted": "source-clockify"},
        {"original": "Close.com", "formatted": "source-close-com"},
        {"original": "Coda", "formatted": "source-coda"},
        {"original": "Coin API", "formatted": "source-coin-api"},
        {"original": "CoinGecko Coins", "formatted": "source-coingecko-coins"},
        {"original": "CoinMarketCap", "formatted": "source-coinmarketcap"},
        {"original": "Commcare", "formatted": "source-commcare"},
        {"original": "Commercetools", "formatted": "source-commercetools"},
        {"original": "ConfigCat", "formatted": "source-configcat"},
        {"original": "Confluence", "formatted": "source-confluence"},
        {"original": "ConvertKit", "formatted": "source-convertkit"},
        {"original": "Convex", "formatted": "source-convex"},
        {"original": "Copper", "formatted": "source-copper"},
        {"original": "Datadog", "formatted": "source-datadog"},
        {"original": "Datascope", "formatted": "source-datascope"},
        {"original": "Delighted", "formatted": "source-delighted"},
        {"original": "Dixa", "formatted": "source-dixa"},
        {"original": "Dockerhub", "formatted": "source-dockerhub"},
        {"original": "Dremio", "formatted": "source-dremio"},
        {"original": "Drift", "formatted": "source-drift"},
        {"original": "EmailOctopus", "formatted": "source-emailoctopus"},
        {"original": "Everhour", "formatted": "source-everhour"},
        {"original": "Exchange Rates Api", "formatted": "source-exchange-rates"},
        {"original": "Facebook Marketing", "formatted": "source-facebook-marketing"},
        {"original": "Facebook Pages", "formatted": "source-facebook-pages"},
        {"original": "Fastbill", "formatted": "source-fastbill"},
        {"original": "Fauna", "formatted": "source-fauna"},
        {
            "original": "File (CSV, JSON, Excel, Feather, Parquet)",
            "formatted": "source-file",
        },
        {
            "original": "Firebase Realtime Database",
            "formatted": "source-firebase-realtime-database",
        },
        {"original": "Firebolt", "formatted": "source-firebolt"},
        {"original": "Flexport", "formatted": "source-flexport"},
        {"original": "Freshcaller", "formatted": "source-freshcaller"},
        {"original": "Freshdesk", "formatted": "source-freshdesk"},
        {"original": "Freshsales", "formatted": "source-freshsales"},
        {"original": "Freshservice", "formatted": "source-freshservice"},
        {"original": "Fullstory", "formatted": "source-fullstory"},
        {"original": "Gainsight Px", "formatted": "source-gainsight-px"},
        {"original": "GCS", "formatted": "source-gcs"},
        {"original": "Genesys", "formatted": "source-genesys"},
        {"original": "Lago API", "formatted": "source-getlago"},
        {"original": "GitHub", "formatted": "source-github"},
        {"original": "Gitlab", "formatted": "source-gitlab"},
        {"original": "Glassfrog", "formatted": "source-glassfrog"},
        {"original": "GoCardless", "formatted": "source-gocardless"},
        {"original": "Gong", "formatted": "source-gong"},
        {"original": "Google Ads", "formatted": "source-google-ads"},
        {
            "original": "Google Analytics 4 (GA4)",
            "formatted": "source-google-analytics-v4",
        },
        {"original": "Google Directory", "formatted": "source-google-directory"},
        {"original": "Google Drive", "formatted": "source-google-drive"},
        {
            "original": "Google PageSpeed Insights",
            "formatted": "source-google-pagespeed-insights",
        },
        {
            "original": "Google Search Console",
            "formatted": "source-google-search-console",
        },
        {"original": "Google Sheets", "formatted": "source-google-sheets"},
        {"original": "Google Webfonts", "formatted": "source-google-webfonts"},
        {"original": "Greenhouse", "formatted": "source-greenhouse"},
        {"original": "Gridly", "formatted": "source-gridly"},
        {"original": "Gutendex", "formatted": "source-gutendex"},
        {"original": "Harvest", "formatted": "source-harvest"},
        {"original": "Hellobaton", "formatted": "source-hellobaton"},
        {"original": "Hubplanner", "formatted": "source-hubplanner"},
        {"original": "HubSpot", "formatted": "source-hubspot"},
        {"original": "Insightly", "formatted": "source-insightly"},
        {"original": "Instagram", "formatted": "source-instagram"},
        {"original": "Instatus", "formatted": "source-instatus"},
        {"original": "Intercom", "formatted": "source-intercom"},
        {"original": "Intruder", "formatted": "source-intruder"},
        {"original": "IP2Whois", "formatted": "source-ip2whois"},
        {"original": "Iterable", "formatted": "source-iterable"},
        {"original": "Jira", "formatted": "source-jira"},
        {"original": "K6 Cloud", "formatted": "source-k6-cloud"},
        {"original": "Klarna", "formatted": "source-klarna"},
        {"original": "Klaus Api", "formatted": "source-klaus-api"},
        {"original": "Klaviyo", "formatted": "source-klaviyo"},
        {"original": "Kyriba", "formatted": "source-kyriba"},
        {"original": "KYVE", "formatted": "source-kyve"},
        {"original": "LaunchDarkly", "formatted": "source-launchdarkly"},
        {"original": "Lemlist", "formatted": "source-lemlist"},
        {"original": "Lever Hiring", "formatted": "source-lever-hiring"},
        {"original": "LinkedIn Ads", "formatted": "source-linkedin-ads"},
        {"original": "LinkedIn Pages", "formatted": "source-linkedin-pages"},
        {"original": "Linnworks", "formatted": "source-linnworks"},
        {"original": "Lokalise", "formatted": "source-lokalise"},
        {"original": "Looker", "formatted": "source-looker"},
        {"original": "Mailchimp", "formatted": "source-mailchimp"},
        {"original": "MailerLite", "formatted": "source-mailerlite"},
        {"original": "MailerSend", "formatted": "source-mailersend"},
        {"original": "Mailgun", "formatted": "source-mailgun"},
        {"original": "Mailjet Mail", "formatted": "source-mailjet-mail"},
        {"original": "Mailjet SMS", "formatted": "source-mailjet-sms"},
        {"original": "Marketo", "formatted": "source-marketo"},
        {"original": "Merge API", "formatted": "source-merge"},
        {"original": "Metabase", "formatted": "source-metabase"},
        {"original": "Microsoft Dataverse", "formatted": "source-microsoft-dataverse"},
        {"original": "Microsoft OneDrive", "formatted": "source-microsoft-onedrive"},
        {"original": "Microsoft SharePoint", "formatted": "source-microsoft-sharepoint"},
        {"original": "Microsoft Teams", "formatted": "source-microsoft-teams"},
        {"original": "Mixpanel", "formatted": "source-mixpanel"},
        {"original": "Monday", "formatted": "source-monday"},
        {"original": "My Hours", "formatted": "source-my-hours"},
        {"original": "n8n", "formatted": "source-n8n"},
        {"original": "Nasa", "formatted": "source-nasa"},
        {"original": "Netsuite", "formatted": "source-netsuite"},
        {"original": "News API", "formatted": "source-news-api"},
        {"original": "Newsdata", "formatted": "source-newsdata"},
        {"original": "Notion", "formatted": "source-notion"},
        {"original": "New York Times", "formatted": "source-nytimes"},
        {"original": "Okta", "formatted": "source-okta"},
        {"original": "Omnisend", "formatted": "source-omnisend"},
        {"original": "OneSignal", "formatted": "source-onesignal"},
        {"original": "Open Exchange Rates", "formatted": "source-open-exchange-rates"},
        {"original": "Openweather", "formatted": "source-openweather"},
        {"original": "Opsgenie", "formatted": "source-opsgenie"},
        {"original": "Orb", "formatted": "source-orb"},
        {"original": "Orbit", "formatted": "source-orbit"},
        {"original": "Oura", "formatted": "source-oura"},
        {"original": "Outbrain Amplify", "formatted": "source-outbrain-amplify"},
        {"original": "Outreach", "formatted": "source-outreach"},
        {"original": "Pardot", "formatted": "source-pardot"},
        {"original": "PartnerStack", "formatted": "source-partnerstack"},
        {"original": "Paypal Transaction", "formatted": "source-paypal-transaction"},
        {"original": "Paystack", "formatted": "source-paystack"},
        {"original": "Pendo", "formatted": "source-pendo"},
        {"original": "PersistIq", "formatted": "source-persistiq"},
        {"original": "Pexels API", "formatted": "source-pexels-api"},
        {"original": "Pinterest", "formatted": "source-pinterest"},
        {"original": "Pipedrive", "formatted": "source-pipedrive"},
        {"original": "Pivotal Tracker", "formatted": "source-pivotal-tracker"},
        {"original": "Plaid", "formatted": "source-plaid"},
        {"original": "Plausible", "formatted": "source-plausible"},
        {"original": "Pocket", "formatted": "source-pocket"},
        {"original": "PokeAPI", "formatted": "source-pokeapi"},
        {"original": "Polygon Stock API", "formatted": "source-polygon-stock-api"},
        {"original": "PostHog", "formatted": "source-posthog"},
        {"original": "Postmark App", "formatted": "source-postmarkapp"},
        {"original": "PrestaShop", "formatted": "source-prestashop"},
        {"original": "Primetric", "formatted": "source-primetric"},
        {"original": "Public Apis", "formatted": "source-public-apis"},
        {"original": "Punk API", "formatted": "source-punk-api"},
        {"original": "PyPI", "formatted": "source-pypi"},
        {"original": "Qualaroo", "formatted": "source-qualaroo"},
        {"original": "QuickBooks", "formatted": "source-quickbooks"},
        {"original": "Railz", "formatted": "source-railz"},
        {"original": "RD Station Marketing", "formatted": "source-rd-station-marketing"},
        {"original": "Recharge", "formatted": "source-recharge"},
        {"original": "Recreation.gov API", "formatted": "source-recreation"}, ##Need to repeat this one!
        {"original": "Recruitee", "formatted": "source-recruitee"},
        {"original": "Recurly", "formatted": "source-recurly"},
        {"original": "Reply.io", "formatted": "source-reply-io"},
        {"original": "Retently", "formatted": "source-retently"},
        {"original": "Ringcentral", "formatted": "source-ringcentral"},
        {"original": "RKI Covid", "formatted": "source-rki-covid"},
        {"original": "Rocket.chat", "formatted": "source-rocket-chat"},
        {"original": "Rss", "formatted": "source-rss"},
        {"original": "S3", "formatted": "source-s3"},
        {"original": "Salesforce", "formatted": "source-salesforce"},
        {"original": "SalesLoft", "formatted": "source-salesloft"},
        {"original": "SAP Fieldglass", "formatted": "source-sap-fieldglass"},
        {"original": "Secoda", "formatted": "source-secoda"},
        {"original": "Sendgrid", "formatted": "source-sendgrid"},
        {"original": "Sendinblue", "formatted": "source-sendinblue"},
        {"original": "Senseforce", "formatted": "source-senseforce"},
        {"original": "Sentry", "formatted": "source-sentry"},
        {"original": "Serpstat", "formatted": "source-serpstat"},
        {"original": "SFTP Bulk", "formatted": "source-sftp-bulk"},
        {"original": "Shopify", "formatted": "source-shopify"},
        {"original": "Shortio", "formatted": "source-shortio"},
        {"original": "Slack", "formatted": "source-slack"},
        {"original": "Smaily", "formatted": "source-smaily"},
        {"original": "SmartEngage", "formatted": "source-smartengage"},
        {"original": "Smartsheets", "formatted": "source-smartsheets"},
        {"original": "Snapchat Marketing", "formatted": "source-snapchat-marketing"},
        {"original": "Sonar Cloud", "formatted": "source-sonar-cloud"},
        {"original": "SpaceX API", "formatted": "source-spacex-api"},
        {"original": "Square", "formatted": "source-square"},
        {"original": "Statuspage.io API", "formatted": "source-statuspage"},
        {"original": "Strava", "formatted": "source-strava"},
        {"original": "Stripe", "formatted": "source-stripe"},
        {"original": "SurveySparrow", "formatted": "source-survey-sparrow"},
        {"original": "SurveyCTO", "formatted": "source-surveycto"},
        {"original": "SurveyMonkey", "formatted": "source-surveymonkey"},
        {"original": "Tempo", "formatted": "source-tempo"},
        {"original": "The Guardian API", "formatted": "source-the-guardian-api"},
        {"original": "TikTok Marketing", "formatted": "source-tiktok-marketing"},
        {"original": "Timely", "formatted": "source-timely"},
        {"original": "TMDb", "formatted": "source-tmdb"},
        {"original": "Todoist", "formatted": "source-todoist"},
        {"original": "Toggl", "formatted": "source-toggl"},
        {"original": "TPLcentral", "formatted": "source-tplcentral"},
        {"original": "Trello", "formatted": "source-trello"},
        {"original": "TrustPilot", "formatted": "source-trustpilot"},
        {"original": "TVMaze Schedule", "formatted": "source-tvmaze-schedule"},
        {"original": "Twilio Taskrouter", "formatted": "source-twilio-taskrouter"},
        {"original": "Twilio", "formatted": "source-twilio"},
        {"original": "Twitter", "formatted": "source-twitter"},
        {"original": "Tyntec SMS", "formatted": "source-tyntec-sms"},
        {"original": "Typeform", "formatted": "source-typeform"},
        {"original": "US Census", "formatted": "source-us-census"},
        {"original": "Vantage", "formatted": "source-vantage"},
        {"original": "Visma Economic", "formatted": "source-visma-economic"},
        {"original": "Vitally", "formatted": "source-vitally"},
        {"original": "Waiteraid", "formatted": "source-waiteraid"},
        {"original": "Weatherstack", "formatted": "source-weatherstack"},
        {"original": "Webflow", "formatted": "source-webflow"},
        {"original": "Whisky Hunter", "formatted": "source-whisky-hunter"},
        {"original": "Wikipedia Pageviews", "formatted": "source-wikipedia-pageviews"},
        {"original": "WooCommerce", "formatted": "source-woocommerce"},
        {"original": "Workable", "formatted": "source-workable"},
        {"original": "WorkRamp", "formatted": "source-workramp"},
        {"original": "Wrike", "formatted": "source-wrike"},
        {"original": "Xero", "formatted": "source-xero"},
        {"original": "xkcd", "formatted": "source-xkcd"},
        {"original": "Yahoo Finance Price", "formatted": "source-yahoo-finance-price"},
        {"original": "Yandex Metrica", "formatted": "source-yandex-metrica"},
        {"original": "Yotpo", "formatted": "source-yotpo"},
        {"original": "Younium", "formatted": "source-younium"},
        {"original": "YouTube Analytics", "formatted": "source-youtube-analytics"},
        {
            "original": "Zapier Supported Storage",
            "formatted": "source-zapier-supported-storage",
        },
        {"original": "Zendesk Chat", "formatted": "source-zendesk-chat"},
        {"original": "Zendesk Sunshine", "formatted": "source-zendesk-sunshine"},
        {"original": "Zendesk Support", "formatted": "source-zendesk-support"},
        {"original": "Zendesk Talk", "formatted": "source-zendesk-talk"},
        {"original": "Zenefits", "formatted": "source-zenefits"},
        {"original": "Zenloop", "formatted": "source-zenloop"},
        {"original": "ZohoCRM", "formatted": "source-zoho-crm"},
        {"original": "Zoom", "formatted": "source-zoom"},
]
